/**
 * Códigos de Erro Padrão
 * Códigos de erro estruturados para o projeto
 */

const ERROR_CODES = {
  // Erros de Validação (4xx)
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  MISSING_HEADER: 'MISSING_HEADER',
  INVALID_GATEWAY: 'INVALID_GATEWAY',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  TENANT_MISMATCH: 'TENANT_MISMATCH',

  // Erros de Autenticação (401)
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TENANT: 'INVALID_TENANT',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Erros de Idempotência (409)
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  IDEMPOTENCY_MISMATCH: 'IDEMPOTENCY_MISMATCH',

  // Erros de Gateway (5xx)
  GATEWAY_ERROR: 'GATEWAY_ERROR',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  GATEWAY_UNAVAILABLE: 'GATEWAY_UNAVAILABLE',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',

  // Erros de Sistema
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  QUEUE_ERROR: 'QUEUE_ERROR',

  // Erros de Negócio
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED'
};

const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

module.exports = {
  ERROR_CODES,
  HTTP_STATUS_CODES
};
